### ISSUE TITLE
LISTENER - Returned listed on markplace

### ISSUE THREAD

**Issue by future2back** [niklas-pernter/axie-infinity-status-discord-bot#3]
As its not solved i will reopen. if you have any solution.

This way we can listen to our own channels.

```
import discord

"""
AXIES
#aqua-listings
#beast-listings
#plant--listings
#bird-listings
#bug-listings
#reptile-listings
#dawn-listings
#mech-listings
#dusk-listings
#egg-listings

LANDS
#land-listings

"""

intents = discord.Intents.default()
intents.messages = True

client = discord.Client(intents = intents)
guild = discord.Guild
messages =  []


print("Bot started")
@client.event
async def on_message(message):
    
    channelIDsToListen = [ CHANNELID_HERE, CHANNELID_HERE] # put the channels that you want to listen to here

    if message.channel.id in channelIDsToListen:

        if message.content != "" :
 
            messages.append(message.content)

        print("New message: " + message.content)
    
client.run('TOKEN_HERE')
```

**Comment by niklas-pernter** [comment]
So what you're trying to do is only listen to a specific channel, right? if thats the case. I already have a quick fix for you

```python
import discord

"""
AXIES
#aqua-listings
#beast-listings
#plant--listings
#bird-listings
#bug-listings
#reptile-listings
#dawn-listings
#mech-listings
#dusk-listings
#egg-listings

LANDS
#land-listings

"""

intents = discord.Intents.default()
intents.messages = True

client = discord.Client(intents = intents)
guild = discord.Guild
messages =  []

#channel id
allowed_channels = [870383937866842182]


@client.event
async def on_ready():
    print('\n We are logged in as {0.user}'.format(client))
    await client.change_presence(activity=discord.Activity(type=discord.ActivityType.listening, name="!server"))


@client.event
async def on_message(message):
    # If the author is the robot itself, then do nothing!
    if message.author == client.user:
        return
    #check if the message comes from an allowed channel
    if message.channel.id in allowed_channels:
        await message.reply("Hello World")
        return
    else:
        #command attempted in non command channel - redirect user
        await message.channel.send('Not allowed in this channel')
        return
    
client.run('ODgwNzc3OTI5NDk4NDM5Njkw.YSjOXg.fS5-4nrwKXUtAaxPlfUcSQo9Ecs')
```

**Comment by future2back** [comment]
> 
> 
> So what you're trying to do is only listen to a specific channel, right? if thats the case. I already have a quick fix for you
> 
> ```python
> import discord
> 
> """
> AXIES
> #aqua-listings
> #beast-listings
> #plant--listings
> #bird-listings
> #bug-listings
> #reptile-listings
> #dawn-listings
> #mech-listings
> #dusk-listings
> #egg-listings
> 
> LANDS
> #land-listings
> 
> """
> 
> intents = discord.Intents.default()
> intents.messages = True
> 
> client = discord.Client(intents = intents)
> guild = discord.Guild
> messages =  []
> 
> #channel id
> allowed_channels = [870383937866842182]
> 
> 
> @client.event
> async def on_ready():
>     print('\n We are logged in as {0.user}'.format(client))
>     await client.change_presence(activity=discord.Activity(type=discord.ActivityType.listening, name="!server"))
> 
> 
> @client.event
> async def on_message(message):
>     # If the author is the robot itself, then do nothing!
>     if message.author == client.user:
>         return
>     #check if the message comes from an allowed channel
>     if message.channel.id in allowed_channels:
>         await message.reply("Hello World")
>         return
>     else:
>         #command attempted in non command channel - redirect user
>         await message.channel.send('Not allowed in this channel')
>         return
>     
> client.run('TOKEN_HERE')
> ```

Hello bro, thanks for replying!

Were you able to listen to marketplace listings channels?

**Comment by niklas-pernter** [comment]
Oh... I misunderstood you. Ill try to listen to the official axie discord channels.

**Comment by niklas-pernter** [comment]
Oh and I found out, that listening to server-external channels as a "not-verified-bot" is against discords policy. 

Heres why
* Your account needs to be a normal account controlled by a bot
* Listen to channel activities and send to your server.

And programming a bot that joins the server and listens to channel activities is a bit beyond my coding skills with this api
